######################################################################
# Automatically generated by qmake (1.04a) Sun Jan 4 14:46:13 2004
######################################################################

QT += network
TEMPLATE = app
INCLUDEPATH += .
INCLUDEPATH += /opt/local/include/Alta
LIBS += -L/opt/local/lib -lADT_L1_Linux_x86_64_v3310 -lADT_L0_Linux_x86_64_v3310

# Input
HEADERS += A429.h
SOURCES += ctrl.cc A429.cc
